# Generated by Django 3.0.3 on 2020-06-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20200624_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cr_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cr_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='cr_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
