# Generated by Django 3.0.3 on 2020-06-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20200624_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.Profile'),
        ),
    ]
