# Generated by Django 3.0.3 on 2020-06-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20200625_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(null=True, upload_to='images\\'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_profile', to='social.Profile'),
        ),
    ]
